(()=>{
const {defaults,providerPresets,demoNews,normalizeSourceSettings,normalizeNews,classifyNews,productImage,productUrl}=globalThis.HotData;
const {matchProducts,newsKeywords}=globalThis.HotMatching;
const {dedupeBatch,recentPublication}=globalThis.HotDedupe;
const {generate}=globalThis.HotLLM;
const {decide}=globalThis.HotAuto;
const evaluation=globalThis.HotEvaluation;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function formatPublishedAt(value){if(!value)return '来源未提供';const date=new Date(value);return Number.isNaN(date.getTime())?'来源未提供':new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(date)}
const fileMode=location.protocol==='file:';
const localConfigKey='hot-workbench-config-v1',localRecordsKey='hot-workbench-records-v1';
function localGet(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
const state={step:1,uiMode:'manual',autoActive:false,autoRunning:false,autoItems:[],autoRunAt:null,autoNewsMode:'demo',autoSources:[],autoUnread:0,autoController:null,autoTimer:null,settings:{...defaults},configSource:'default',server:false,news:dedupeBatch(normalizeNews(demoNews)),newsMode:'demo',sources:[],selectedNews:null,products:[],recommendedProducts:[],copy:'',variant:'活力种草',toneDrafts:new Map(),candidates:[],activeCandidate:null,generating:false,generatedOnce:false,metrics:null,validation:null,repairTrace:[],repairing:false,repairController:null,approved:false,published:false,filter:'全部',query:'',records:localGet(localRecordsKey,[]),fetching:false,controller:null};
const titles=['新闻抓取','建议匹配商品','匹配商品','创作文案','审核并发送'];
const descriptions=['追踪公开热榜与订阅源，先判断借势风险，再挑选热点。','查看系统按消费场景计算的推荐与推荐理由。','在完整商品库中进一步筛选，确认最终推广商品。','基于当前热点和商品生成微博文案，支持微调与复制。','检查文案与风险状态，预览后完成模拟发布。'];
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3200)}
async function api(path,options={}){if(fileMode)throw new Error('本地服务未启动');const response=await fetch(path,{...options,signal:options.signal||AbortSignal.timeout(12000)});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||`HTTP ${response.status}`);return response.json()}
async function saveRecord(entry){const record={time:new Date().toISOString(),...entry};if(state.server)try{const result=await api('/api/log',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(entry)});if(result.duplicate)return null}catch{}state.records.push(record);localStorage.setItem(localRecordsKey,JSON.stringify(state.records.slice(-500)));return record}
function mergeRecords(serverRecords,localRecords){const merged=[...serverRecords];for(const local of localRecords){const index=merged.findIndex(row=>row.type===local.type&&row.title===local.title&&row.mode===local.mode&&Math.abs(new Date(row.time)-new Date(local.time))<5000);if(index<0){merged.push(local);continue}const server=merged[index];merged[index]={...local,...server,copy:server.copy||local.copy||'',keywords:server.keywords?.length?server.keywords:local.keywords||[]};}return merged}
async function refreshSettings(){
  const oldProducts=state.products.map(id=>state.settings.products?.find(product=>product.id===id));
  const local=localGet(localConfigKey,null);state.settings={...defaults,...local,...normalizeSourceSettings(local||{}),products:local?.products?.length?local.products:defaults.products,promptTemplates:{...defaults.promptTemplates,...local?.promptTemplates},evaluation:globalThis.HotData.normalizeEvaluationSettings(local?.evaluation)};
  state.configSource=local?'browser':'default';state.server=false;
  if(!fileMode)try{const result=await api('/api/config');state.server=true;if(result.config){state.settings={...defaults,...result.config,...normalizeSourceSettings(result.config),evaluation:globalThis.HotData.normalizeEvaluationSettings(result.config.evaluation),apiKey:local?.apiKey||''};state.configSource='server'}}catch{}
  if(!Array.isArray(state.settings.creativeStyles)||!state.settings.creativeStyles.length)state.settings.creativeStyles=defaults.creativeStyles;
  if(!Array.isArray(state.settings.tonePresets)||!state.settings.tonePresets.length)state.settings.tonePresets=defaults.tonePresets;
  if(!state.settings.tonePresets.includes(state.variant)){state.variant=state.settings.tonePresets[0];resetAfterProduct()}
  const available=new Set(state.settings.products.map(product=>product.id));
  state.products=state.products.filter(id=>available.has(id));
  state.recommendedProducts=state.recommendedProducts.filter(id=>available.has(id));
  const newProducts=state.products.map(id=>state.settings.products.find(product=>product.id===id));
  if(JSON.stringify(oldProducts)!==JSON.stringify(newProducts))resetAfterProduct();
  $('#connection').textContent=state.server?'本地服务已连接':'离线演示可用';$('.status-dot').style.background=state.server?'var(--success)':'var(--warn)';
}
async function init(){
  await refreshSettings();if(state.server)try{const logs=await api('/api/records');state.records=mergeRecords(logs.records,state.records)}catch{}
  $('#clock').textContent=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  render();
}
function currentNews(){return state.news.find(n=>n.id===state.selectedNews)||null}
function picked(){return state.products.map(id=>state.settings.products.find(p=>p.id===id)).filter(Boolean)}
function matches(){return matchProducts(currentNews(),state.settings.products)}
function resetAfterNews(){state.products=[];state.recommendedProducts=[];resetAfterProduct()}
function resetAfterProduct(preserveToneDrafts=false){if(!preserveToneDrafts)state.toneDrafts.clear();if(state.controller)state.controller.abort();state.controller=null;if(state.repairController)state.repairController.abort();state.repairController=null;state.copy='';state.candidates=[];state.activeCandidate=null;state.metrics=null;state.validation=null;state.repairTrace=[];state.repairing=false;state.generatedOnce=false;state.approved=false;state.published=false;state.generating=false}
function composeContextKey(){return JSON.stringify({news:currentNews(),products:picked()})}
function selectVariant(variant){
  if(state.generating||state.repairing||variant===state.variant||!state.settings.tonePresets.includes(variant))return;
  syncActiveCandidate();
  if(state.copy||state.candidates.length||state.generatedOnce){
    // 按语调保留整组候选和当前编辑状态；热点/商品改变时统一作废。
    state.toneDrafts.set(state.variant,JSON.parse(JSON.stringify({contextKey:composeContextKey(),copy:state.copy,candidates:state.candidates,activeCandidate:state.activeCandidate,metrics:state.metrics,validation:state.validation,repairTrace:state.repairTrace,generatedOnce:state.generatedOnce})));
  }else state.toneDrafts.delete(state.variant);
  resetAfterProduct(true);state.variant=variant;
  const draft=state.toneDrafts.get(variant);
  if(draft&&draft.contextKey===composeContextKey()){
    const restored=JSON.parse(JSON.stringify(draft));
    for(const key of ['copy','candidates','activeCandidate','metrics','repairTrace','generatedOnce'])state[key]=restored[key];
    for(const candidate of state.candidates)candidate.validation=candidate.text?evaluation.verify(candidate.text,currentNews(),picked(),state.settings.evaluation):null;
    state.validation=state.copy?evaluation.verify(state.copy,currentNews(),picked(),state.settings.evaluation):null;
    syncActiveCandidate();
  }else state.toneDrafts.delete(variant);
  render();
}
function selectNews(id,auto=false){const n=state.news.find(x=>x.id===id);if(!n)return;if(n.risk.level==='blocked'){toast(`禁止借势：${n.risk.reason}。该热点无法选中。`);return}if(auto&&recentPublication(n.title,state.records)){toast('自动流程已跳过：近三天发布过相似热点');return}
  if(state.selectedNews!==id){state.selectedNews=id;resetAfterNews()}
  const old=recentPublication(n.title,state.records);if(old&&!auto)toast('已选为爆款热点；提醒：近三天已有发布记录，手工模式仍可继续。');else if(n.risk.level==='review')toast('已选为爆款热点；该话题需人工判断，请谨慎处理。');else toast('已选为爆款热点，点击“下一步”查看建议商品');render();}
function toggleProduct(id){const before=state.products.join(',');const adding=!state.products.includes(id);state.products=adding?[...state.products,id]:state.products.filter(x=>x!==id);state.recommendedProducts=state.recommendedProducts.filter(x=>state.products.includes(x));if(adding&&state.step===2)state.recommendedProducts.push(id);if(state.products.join(',')!==before)resetAfterProduct();render()}
function completedSteps(){return [Boolean(currentNews()),state.recommendedProducts.length>0,state.products.length>0,Boolean(state.copy),state.published]}
function summary(i){const n=currentNews();return [n?`已选: ${n.title}`:state.newsMode==='live'?`${state.news.length} 条实时热点`:`${state.news.length} 条演示热点`,state.recommendedProducts.length?`已采纳 ${state.recommendedProducts.length} 件推荐商品`:n?'系统智能推荐':'等待选择热点',state.products.length?`已绑定 ${state.products.length} 件商品`:'商品库深度筛选',state.copy?`已生成 ${state.copy.length} 字文案`:'等待创作文案',state.published?'已模拟发布':state.approved?'审核已通过':'等待审核'][i]}
function render(){
  $('#manualMode').classList.toggle('active',state.uiMode==='manual');$('#autoMode').classList.toggle('active',state.uiMode==='auto');$('#manualMode').setAttribute('aria-pressed',String(state.uiMode==='manual'));$('#autoMode').setAttribute('aria-pressed',String(state.uiMode==='auto'));const alert=$('#autoAlertCount');alert.hidden=!state.autoUnread;alert.textContent=state.autoUnread;
  if(state.uiMode==='auto'){renderAuto();return}
  $('.sidebar-head span:first-child').textContent='营销流水线';$('.side-count').textContent='01 — 05';
  $('#pageTitle').textContent=titles[state.step-1];$('#pageDesc').textContent=descriptions[state.step-1];
  $('#dataSource').textContent=state.newsMode==='live'?'实时抓取数据':'当前是演示数据';$('#dataSource').className=`pill ${state.newsMode}`;
  const done=completedSteps();$('#steps').innerHTML=titles.map((t,i)=>`<button class="step ${state.step===i+1?'active':done[i]?'completed':''}" data-step="${i+1}" ${state.step===i+1?'aria-current="step"':''} aria-label="第 ${i+1} 步 ${esc(t)}${done[i]?'，已完成':''}"><span class="step-number">${done[i]&&state.step!==i+1?'✓':i+1}</span><span class="step-copy"><span class="step-label">Step ${i+1} · ${t}</span><span class="step-summary" title="${esc(summary(i))}">${esc(summary(i))}</span></span></button>`).join('');
  const n=currentNews();$('#breadcrumb').innerHTML=`<strong>当前链路</strong><span class="sep">/</span><span class="${n?'current':''}">${n?esc(n.title):'未选择热点'}</span><span class="sep">›</span><span class="${state.products.length?'current':''}">${state.products.length?`已选 ${state.products.length} 件商品`:'待匹配商品'}</span><span class="sep">›</span><span class="${state.copy?'current':''}">${state.copy?'文案已生成':'待创作文案'}</span><span class="sep">›</span><span class="${state.published?'current':''}">${state.published?'已发布':state.approved?'审核通过':'待审核'}</span>`;
  $('#workspace').innerHTML=[renderNews,renderSuggested,renderLibrary,renderCompose,renderReview][state.step-1]();
}
function renderAutoPost(record){
  const keywords=newsKeywords({title:record.title,keywords:record.keywords}),products=Array.isArray(record.products)?record.products.filter(Boolean):[],copy=String(record.copy||'').trim();
  return `<article class="auto-send-card"><div class="auto-send-card-head"><span class="badge good">已发送</span><time>${esc(formatPublishedAt(record.time))}</time></div><div class="auto-send-field"><span>新闻标题</span><strong>${esc(record.title||'未记录标题')}</strong></div><div class="auto-send-field"><span>关键词</span><div class="auto-send-keywords">${keywords.length?keywords.map(word=>`<span>#${esc(word)}#</span>`).join(''):'<em>历史记录未保存关键词</em>'}</div></div><div class="auto-send-field"><span>商品名称</span><strong>${products.length?products.map(esc).join('、'):'未记录商品'}</strong></div><div class="auto-send-field"><span>微博文案内容</span><p class="auto-send-copy ${copy?'':'missing'}">${copy?esc(copy):'历史记录未保存微博正文'}</p></div></article>`
}
function renderAuto(){
  const sent=state.autoItems.filter(x=>x.status==='sent').length,skipped=state.autoItems.filter(x=>x.status==='skipped').length,failed=state.autoItems.filter(x=>x.status==='failed').length;
  const posts=[...state.records].filter(x=>x.type==='publish'&&x.mode==='auto-simulation').reverse().filter((row,index,rows)=>rows.findIndex(x=>x.title===row.title)===index).slice(0,30);
  $('#pageTitle').textContent='自动营销流水线';$('#pageDesc').textContent='热度过线且完成商品匹配后自动生成文案并模拟发送；每两分钟复查一次。';
  $('#dataSource').textContent=state.autoNewsMode==='live'?'实时抓取数据':'当前是演示数据';$('#dataSource').className=`pill ${state.autoNewsMode}`;
  $('.sidebar-head span:first-child').textContent='自动流水线';$('.side-count').textContent='AUTO';
  $('#steps').innerHTML=[['01','抓取热点',state.autoRunning?'正在检查来源':state.autoRunAt?`上次 ${formatPublishedAt(state.autoRunAt)}`:'等待启动'],['02','风险与去重',`${skipped} 条已跳过`],['03','热度与匹配',`阈值 ${Number(state.settings.autoThreshold).toLocaleString('zh-CN')}`],['04','自动生成',state.settings.mode==='mock'?'本地模拟文案':state.settings.model],['05','模拟发送',`${sent} 条已发送`]].map((x,i)=>`<div class="step auto-step ${state.autoRunning&&i===0?'active':''}"><span class="step-number">${x[0]}</span><span><span class="step-label">${esc(x[1])}</span><span class="step-summary">${esc(x[2])}</span></span></div>`).join('');
  $('#breadcrumb').innerHTML='<strong>自动链路</strong><span class="sep">/</span><span>实时热点</span><span class="sep">›</span><span>风险拦截</span><span class="sep">›</span><span>热度与商品匹配</span><span class="sep">›</span><span>文案生成</span><span class="sep">›</span><span class="current">模拟发送清单</span>';
  $('#workspace').innerHTML=`<div class="auto-hero card"><div><span class="badge ${state.autoActive?'good':'warning'}">${state.autoRunning?'运行中':state.autoActive?'监控中 · 每 2 分钟':'已暂停'}</span><h2>让安全、相关的热点自动进入发送队列</h2><p>高风险及需人工判断的话题直接跳过；没有热度或匹配商品的新闻也不会发送。</p></div><div class="toolbar"><button class="button ${state.autoActive?'':'primary'}" id="${state.autoActive?'stopAuto':'startAuto'}">${state.autoActive?'暂停自动模式':'启动自动模式'}</button><button class="button" id="runAuto" ${state.autoRunning?'disabled':''}>${state.autoRunning?'<span class="spinner"></span> 正在运行':'立即运行一次'}</button></div></div>
  <div class="auto-stats"><div class="card stat"><label>本轮已发送</label><strong>${sent}<small>条</small></strong></div><div class="card stat"><label>已跳过</label><strong>${skipped}<small>条</small></strong></div><div class="card stat"><label>执行失败</label><strong>${failed}<small>条</small></strong></div><div class="card stat"><label>最近运行</label><strong class="auto-time">${state.autoRunAt?esc(formatPublishedAt(state.autoRunAt)):'尚未运行'}</strong></div></div>
  <div class="auto-grid"><div><div class="card auto-control"><div class="content-head"><div><h2>触发条件</h2><p>热度达到阈值，且安全、未重复、商品匹配成功，才会发送。</p></div></div><div class="auto-threshold"><label class="field">最低新闻热度<input id="autoThreshold" type="number" min="0" step="1" value="${Number(state.settings.autoThreshold)}"></label><button class="button primary" id="saveAutoThreshold">保存阈值</button><small class="auto-threshold-hint">只有提供数字热度的来源参与自动发送；演示数据可用较低阈值测试。</small></div><div class="auto-rule">安全风险通过 <span>→</span> 三天内未发送 <span>→</span> 热度达标 <span>→</span> 商品场景匹配 <span>→</span> 文案安全检查 <span>→</span> 模拟发送</div><div class="info-box">当前文案方式：${state.settings.mode==='mock'?'本地模拟':state.settings.mode==='proxy'?'本地服务中转':'浏览器直连'}。自动发送仅为工作台模拟，不会向真实微博账号发帖。配置来自${state.configSource==='server'?'服务端':state.configSource==='browser'?'浏览器本机':'内置默认值'}。</div></div><div class="card auto-decisions"><div class="content-head"><div><h2>本轮处理明细</h2><p>${state.autoItems.length} 条新闻，逐条展示判断结果</p></div></div>${state.autoItems.length?`<div class="auto-list">${state.autoItems.map(item=>`<div class="auto-row"><span class="badge ${item.status==='sent'?'good':item.status==='failed'?'danger':item.status==='running'?'purple':'warning'}">${item.status==='sent'?'已发送':item.status==='failed'?'失败':item.status==='running'?'处理中':'已跳过'}</span><div><strong>${esc(item.title)}</strong><small>${esc(item.reason)}</small>${item.trace?.length?`<div class="auto-repair-trace">${item.trace.map(row=>`<small>第 ${row.round} 轮 ${row.before} → ${row.after} 分 · ${row.accepted?'已采纳':'保留原稿'} · 修复：${esc(row.fixed.join('、')||'无')} · 剩余：${esc(row.remaining.join('、')||'无')}</small>`).join('')}</div>`:''}</div></div>`).join('')}</div>`:'<div class="auto-empty">运行后将在这里显示新闻筛选、跳过和发送原因。</div>'}</div></div><div class="card auto-send"><div class="content-head"><div><h2>自动发送清单 <span class="badge purple">提醒</span></h2><p>已模拟发送的热点会保留在流水中，便于运营复核。</p></div><span class="badge good">${posts.length} 条记录</span></div>${posts.length?`<div class="auto-list auto-send-list">${posts.map(renderAutoPost).join('')}</div>`:'<div class="auto-empty">暂无自动发送记录。启动自动模式后，符合条件的新闻会出现在这里。</div>'}</div>`;
}
function stopAuto(){state.autoActive=false;clearInterval(state.autoTimer);state.autoTimer=null;state.autoController?.abort();render()}
async function runAuto(){if(state.autoRunning)return;await refreshSettings();state.autoRunning=true;state.autoController=new AbortController();const signal=state.autoController.signal;state.autoItems=[];render();
  try{let news=dedupeBatch(normalizeNews(demoNews));state.autoNewsMode='demo';state.autoSources=[];
    if(state.server)try{const result=await api('/api/hot',{signal:AbortSignal.timeout(15000)});if(result.mode==='live'){news=result.news;state.autoNewsMode='live'}state.autoSources=result.sources||[]}catch{state.autoSources=[{name:'本地服务',status:'failed'}]}
    if(signal.aborted)return;
    for(const n of news){if(signal.aborted)break;const choice=decide(n,state.settings,state.records);const item={title:n.title,status:choice.status,reason:choice.reason};state.autoItems.push(item);if(choice.status!=='ready'){render();continue}
      item.status='running';item.reason=`已匹配 ${choice.match.product.name}，正在生成文案`;render();
      const product=choice.match.product;try{let copy='';const result=await generate({news:n,products:[product],settings:{...state.settings,variant:state.settings.tonePresets?.[0]||defaults.tonePresets[0],creativeStyle:state.settings.creativeStyles?.[0]||defaults.creativeStyles[0]},onToken:part=>{copy+=part},signal});if(signal.aborted)break;
        await saveRecord({type:'generate',title:n.title,products:[product.name],mode:`auto-${state.settings.mode}`,model:result.model|| (state.settings.mode==='mock'?'本地模拟':state.settings.model),duration:result.duration,usage:result.usage});
        let validation=evaluation.verify(copy,n,[product],state.settings.evaluation),trace=[];
        if(validation.repairable.length&&Number(state.settings.evaluation?.maxRepairRounds)>0){item.reason=`校验 ${validation.score} 分，正在自动返工`;render();const fixed=await evaluation.repair({copy,news:n,products:[product],settings:{...state.settings,variant:state.settings.tonePresets?.[0]||defaults.tonePresets[0]},signal,onRound:row=>{trace.push(row);item.reason=`第 ${row.round} 轮：${row.accepted?'修复 '+(row.fixed.join('、')||'无'):'未改善，保留原稿'}`;render()}});copy=fixed.text;validation=fixed.machine}
        item.trace=trace;for(const row of trace)await saveRecord({type:'generate',title:n.title,products:[product.name],mode:`auto-repair-${state.settings.mode}`,model:state.settings.mode==='mock'?'本地模拟':state.settings.model,creativeStyle:`返工第 ${row.round} 轮：${row.accepted?'采纳':'保留原稿'}`,duration:row.duration,usage:row.usage});
        if(classifyNews(copy).level!=='safe'||validation.hardFail||validation.score<75){item.status='skipped';item.reason=`转人工复核：${validation.issues.map(x=>x.label+'（'+x.reason+'）').join('；')||'文案风险未通过'}`;render();continue}
        const published=await saveRecord({type:'publish',title:n.title,keywords:newsKeywords(n),products:[product.name],copy,mode:'auto-simulation',repairTrace:trace,validationScore:validation.score});if(!published){item.status='skipped';item.reason='服务端发现近三天已有相似发送记录';render();continue}item.status='sent';item.reason=`热度 ${choice.heat.toLocaleString('zh-CN')} · ${product.name} · 校验 ${validation.score} 分 · 返工 ${trace.filter(x=>x.accepted).length} 轮 · 模拟发送完成`;state.autoUnread++;render();
      }catch(e){if(signal.aborted)break;item.status='failed';item.reason=e.message;await saveRecord({type:'generate',title:n.title,products:[product.name],mode:`auto-${state.settings.mode}`,model:state.settings.mode==='mock'?'本地模拟':state.settings.model,status:'failed'});render()}
    }
    state.autoRunAt=new Date().toISOString();if(!signal.aborted)toast(`自动处理完成：发送 ${state.autoItems.filter(x=>x.status==='sent').length} 条，跳过 ${state.autoItems.filter(x=>x.status==='skipped').length} 条`);
  }finally{state.autoRunning=false;state.autoController=null;render()}}
function startAuto(){if(state.autoActive)return;state.autoActive=true;state.autoTimer=setInterval(()=>{if(state.autoActive)runAuto()},120000);render();runAuto()}
async function saveAutoThreshold(){const value=Number($('#autoThreshold').value);if(!Number.isSafeInteger(value)||value<0){toast('热度阈值须为非负整数');return}try{if(state.server){const result=await api('/api/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({autoThreshold:value})});state.settings={...state.settings,...result.config};state.configSource='server'}else{state.settings.autoThreshold=value;state.configSource='browser'}localStorage.setItem(localConfigKey,JSON.stringify(state.settings));render();toast('自动热度阈值已保存')}catch(e){toast(`阈值未保存：${e.message}`)}}
function renderNews(){const blocked=state.news.filter(n=>n.risk.level==='blocked').length;const review=state.news.filter(n=>n.risk.level==='review').length;return `<div class="stat-grid"><div class="card stat"><label>本轮热点</label><strong>${state.news.length}<small>条</small></strong></div><div class="card stat"><label>禁止借势</label><strong style="color:var(--danger)">${blocked}<small>条已拦截</small></strong></div><div class="card stat"><label>人工判断</label><strong style="color:var(--warn)">${review}<small>条待评估</small></strong></div><div class="card stat"><label>数据来源</label><strong>${state.newsMode==='live'?'实时':'演示'}<small>${state.sources.filter(x=>x.status==='success').length} 源成功</small></strong></div></div>
  <div class="content-head"><div><h2>热点新闻列表</h2><p>选择一条安全热点进入后续流程；手工选择重复热点会提醒但不会阻断。</p></div><div class="toolbar"><button class="button" id="autoPick">✦ 自动挑选</button><button class="button primary" id="fetchHot" ${state.fetching?'disabled':''}>${state.fetching?'<span class="spinner"></span> 正在抓取':'↻ 抓取实时热点'}</button></div></div>
  ${currentNews()?`<div class="news-selection-bar card" role="status"><div class="news-selection-copy"><span class="news-selection-check">✓</span><span><strong>已选为爆款热点</strong><small>${esc(currentNews().title)}</small></span></div><button class="button primary" data-step="2">下一步：建议匹配商品 →</button></div>`:''}
  <div class="layout-two"><div class="news-list">${state.news.map(n=>{const old=recentPublication(n.title,state.records),selected=n.id===state.selectedNews;return `<div class="card news-card ${n.risk.level==='blocked'?'blocked':''} ${selected?'selected':''}" data-news="${esc(n.id)}" role="button" tabindex="${n.risk.level==='blocked'?'-1':'0'}" aria-pressed="${selected}" aria-disabled="${n.risk.level==='blocked'}">${selected?'<span class="selected-hotspot-badge">✓ 已选为爆款热点</span>':''}<span class="rank ${n.rank<=3?'top':''}">${String(n.rank).padStart(2,'0')}</span><div><div class="news-title" title="${esc(n.title)}">${esc(n.title)}</div><div class="news-meta"><span>${esc(n.source)}</span><span>·</span><span>${esc(n.heat||'热榜话题')}</span>${n.sources?.length>1?`<span class="badge purple">${n.sources.length} 个源在报</span>`:''}${old?'<span class="badge warning">三天内发布过</span>':''}</div><div class="news-summary" title="${esc(n.summary||'该来源未提供摘要')}">${esc(n.summary||'该来源未提供摘要')}</div><div class="news-published">发布时间：${esc(formatPublishedAt(n.publishedAt))}</div></div><div class="news-right"><span class="badge ${n.risk.level==='blocked'?'danger':n.risk.level==='review'?'warning':'good'}">${n.risk.level==='blocked'?'禁止借势':n.risk.level==='review'?'人工判断':'可选'}</span><small>${esc(n.risk.reason)}</small></div></div>`}).join('')}</div><div class="card source-panel"><h3>来源运行状态</h3>${state.sources.length?state.sources.map(s=>`<div class="source-row"><div><strong>${esc(s.name)}</strong><small>${s.status==='success'?`抓取 ${s.count} 条 · ${s.duration} ms`:`${esc(s.error||'抓取失败')} · ${s.duration} ms`}</small></div><span class="badge ${s.status==='success'?'good':'danger'}">${s.status==='success'?'成功':'失败'}</span></div>`).join(''):'<div class="info-box">尚未发起抓取。点击“抓取实时热点”查看各来源状态。</div>'}<div class="info-box ${state.newsMode==='demo'?'warning-box':''}">${state.newsMode==='demo'?'当前是演示数据。服务未启动或所有来源不可用时，仍可完整演示流程。':'当前展示真实来源数据；本轮已拦截 '+blocked+' 条高风险热点。'}</div></div></div>`}
function contextStrip(){const n=currentNews();return n?`<div class="card selected-strip"><span>当前热点：<strong>${esc(n.title)}</strong></span><button class="button small" data-step="1">更换热点 ↗</button></div>`:''}
function productCard(p,match){return globalThis.HotCatalog.renderCard(p,{selected:state.products.includes(p.id),match,action:'select'})}
function weiboProduct(p){return `<a class="weibo-product" href="${esc(productUrl(p))}" target="_blank" rel="noopener noreferrer" aria-label="查看${esc(p.name)}商品详情"><img src="${esc(productImage(p))}" alt="${esc(p.name)}商品示意图" loading="lazy"><span class="weibo-product-info"><strong>${esc(p.name)}</strong><small>${esc(p.selling)}</small><span class="weibo-product-bottom"><b>¥${Number(p.price)}</b><span>查看商品详情 ↗</span></span></span></a>`}
function renderSuggested(){const n=currentNews();if(!n)return empty('先选择热点','从新闻抓取页选择一条热点，系统会按消费场景计算商品匹配度。',1);const list=matches();return `${contextStrip()}<div class="content-head"><div><h2>系统建议商品</h2><p>先识别新闻消费场景，再匹配商品卖点；理由和分数可直接核查。</p></div><button class="button" data-step="3">查看完整商品库 →</button></div>${list.length?`<div class="product-grid">${list.map(m=>productCard(m.product,m)).join('')}</div>`:`<div class="card empty"><div class="empty-icon">◇</div><h3>这条热点暂无合适商品</h3><p>${n.risk.level==='review'?'该话题属于时政、财经或争议性事件，需人工判断；系统不推荐商品。':'标题没有命中已配置的消费场景，系统不会硬凑不相关商品。'}</p><button class="button" data-step="1">选择其他热点</button></div>`}${list.length?`<div style="margin-top:18px;text-align:right"><button class="button primary" data-step="3">去商品库继续筛选 →</button></div>`:''}`}
function renderLibrary(){const n=currentNews();if(!n)return empty('先选择热点','选定热点后再筛选和绑定商品。',1);const list=state.settings.products.filter(p=>(state.filter==='全部'||p.category===state.filter)&&(!state.query||[p.name,p.selling,...p.tags].join(' ').toLowerCase().includes(state.query.toLowerCase())));const categories=['全部',...new Set(state.settings.products.map(p=>p.category))];return `${contextStrip()}<div class="content-head"><div><h2>商品库 · ${state.settings.products.length} 件</h2><p>手动筛选与绑定商品。变更商品会自动清除旧文案与审核状态。</p></div><button class="button primary" data-step="4" ${state.products.length?'':'disabled'}>进入文案创作 →</button></div><div class="filterbar"><input id="productSearch" placeholder="搜索商品、卖点或标签" value="${esc(state.query)}">${categories.map(c=>`<button class="chip ${state.filter===c?'active':''}" data-filter="${esc(c)}">${esc(c)}</button>`).join('')}</div>${list.length?`<div class="product-grid">${list.map(p=>productCard(p,null)).join('')}</div>`:'<div class="card empty">没有找到符合条件的商品。</div>'}<div class="info-box">已采纳 ${state.products.length} 件商品。推荐结果仅作为选品参考，请核对事实、价格与使用场景。</div>`}
function variantOptions(){return (state.settings.tonePresets||defaults.tonePresets).map(value=>`<button type="button" class="variant-chip ${state.variant===value?'active':''}" data-variant="${esc(value)}" aria-pressed="${state.variant===value}" ${state.generating||state.repairing?'disabled':''}>${esc(value)}</button>`).join('')}
function composeNewsCard(news){const keywords=newsKeywords(news);return `<div class="compose-news-card"><strong>${esc(news.title)}</strong><div class="compose-news-keywords">${keywords.length?keywords.map(word=>`<span>#${esc(word)}#</span>`).join(''):'<span>未识别到场景关键词</span>'}</div></div>`}
function composeProductCard(product){return `<div class="compose-product-card"><img src="${esc(productImage(product))}" alt="${esc(product.name)}商品示意图" loading="lazy"><div class="compose-product-info"><strong>${esc(product.name)}</strong><div><b>¥${Number(product.price).toLocaleString('zh-CN',{maximumFractionDigits:2})}</b><span> · ${esc(product.selling||'暂无卖点')}</span></div></div></div>`}
function candidateCards(){if(!state.candidates.length)return `<div class="candidate-empty">本次将按 ${state.settings.creativeStyles.length} 种创作风格分别生成候选文案。可在后台调整顺序和要求。</div>`;return `<div class="candidate-grid">${state.candidates.map((candidate,index)=>`<button type="button" class="candidate-card ${state.activeCandidate===candidate.id?'active':''}" data-candidate="${esc(candidate.id)}" ${state.generating||state.repairing?'disabled':''}><span class="candidate-top"><b>版本 ${index+1} · ${esc(candidate.name)}</b><small>${candidate.status==='running'?'生成中…':candidate.status==='done'?`${candidate.text.length} 字`:candidate.status==='failed'?'生成失败':'等待中'}</small></span><span class="candidate-snippet" data-candidate-preview="${esc(candidate.id)}">${candidate.status==='failed'?esc(candidate.error):esc(candidate.text.slice(0,76))||'等待生成…'}</span></button>`).join('')}</div>`}
function validationPanel(){if(!state.copy)return '';const result=state.validation||evaluation.verify(state.copy,currentNews(),picked(),state.settings.evaluation);const problems=result.issues.map(x=>`<div class="validation-issue ${x.hard?'hard':''}"><b>${esc(x.label)} · ${x.hard?'硬伤':'瑕疵'}</b><span>${esc(x.reason)}</span></div>`).join('');const trace=state.repairTrace.length?`<div class="repair-trace">${state.repairTrace.map(x=>`<p>第 ${x.round} 轮 · ${x.before} → ${x.after} 分 · ${x.accepted?'已采纳':'未改善，保留原稿'} · 修复：${esc(x.fixed.join('、')||'无')} · 剩余：${esc(x.remaining.join('、')||'无')}</p>`).join('')}</div>`:'';return `<section class="validation-panel"><div class="validation-head"><strong>机器校验 <span class="score ${result.score>=80?'good':result.score>=60?'mid':'low'}">${result.score} 分</span></strong><span>${result.hardFail?'存在硬伤':result.pass?'全部通过':`${result.issues.length} 项待改`}</span></div>${problems||'<p class="validation-ok">字数、话题、价格和商品等规则均已通过。</p>'}<div class="toolbar"><button type="button" class="button primary" id="repairCopy" ${result.repairable.length&&!state.repairing&&!state.generating?'':'disabled'}>${state.repairing?'正在修正…':'一键修正'}</button><small>只针对可修复问题返工；分数未提高时保留原稿。</small></div>${trace}</section>`}
function syncActiveCandidate(){
  const candidate=state.candidates.find(item=>item.id===state.activeCandidate);
  if(candidate){candidate.text=state.copy;candidate.validation=state.validation;candidate.metrics=state.metrics;candidate.repairTrace=[...state.repairTrace]}
}
async function repairCopy(){
  if(state.repairing||state.generating||!state.copy)return;
  const candidate=state.candidates.find(item=>item.id===state.activeCandidate);
  const news=currentNews(),products=picked(),settings={...state.settings,variant:state.variant};
  const controller=new AbortController();state.repairController=controller;state.repairing=true;render();
  try{
    const result=await evaluation.repair({copy:state.copy,news,products,settings,signal:controller.signal,onRound:row=>{
      if(state.repairController!==controller||controller.signal.aborted)return;
      state.repairTrace.push(row);syncActiveCandidate();render();
    }});
    if(state.repairController!==controller||controller.signal.aborted)return;
    state.copy=result.text;state.validation=result.machine;state.approved=false;state.published=false;
    // 先同步当前版本的正文、校验和修正记录，再异步写流水，避免切换后恢复旧缓存。
    syncActiveCandidate();render();
    for(const row of result.rounds)await saveRecord({type:'generate',title:news.title,products:products.map(p=>p.name),mode:`manual-repair-${settings.mode}`,model:settings.mode==='mock'?'本地模拟':settings.model,creativeStyle:`${candidate?.name||'手工文案'} · 返工第 ${row.round} 轮：${row.accepted?'采纳':'保留原稿'}`,duration:row.duration,usage:row.usage});
    if(state.repairController===controller)toast(result.rounds.some(x=>x.accepted)?`已修正 ${result.rounds.filter(x=>x.accepted).length} 轮，当前 ${result.machine.score} 分`:'返工未提高分数，已保留原稿');
  }catch(error){if(state.repairController===controller&&!controller.signal.aborted)toast(`修正失败：${error.message}`)}
  finally{if(state.repairController===controller){state.repairController=null;state.repairing=false;render()}}
}
function renderCompose(){const n=currentNews(),products=picked();if(!n)return empty('先选择热点','文案需要明确的热点上下文。',1);if(!products.length)return empty('先绑定商品','选择至少一件商品后才能生成文案。',3);return `<div class="compose-layout"><div class="card compose-main"><div class="content-head"><div><h2>微博文案创作</h2><p>每个创作风格独立生成一个版本；选中候选后可微调和审核。</p></div><span class="badge purple">${state.settings.mode==='mock'?'本地模拟':state.settings.mode==='proxy'?'服务中转':'浏览器直连'}</span></div><div class="form-row compose-controls"><div class="field">主打语调<div class="variant-options" role="group" aria-label="主打语调">${variantOptions()}</div></div><button class="button primary" id="generateCopy" ${state.generating||state.repairing?'disabled':''}>${state.generating?'<span class="spinner"></span> 正在生成':state.generatedOnce?'↻ 重新生成文案':'✦ 生成文案'}</button>${state.generating?'<button class="button" id="stopGenerate">停止</button>':''}</div><div class="candidate-section"><div class="candidate-heading"><strong>候选版本</strong><span>${state.candidates.filter(candidate=>candidate.status==='done').length} / ${state.settings.creativeStyles.length} 已完成</span></div>${candidateCards()}</div><textarea id="copyEditor" class="copy-editor ${state.generating?'loading':''}" placeholder="点击“生成文案”，或直接在这里撰写微博正文。" ${state.generating||state.repairing?'readonly':''}>${esc(state.copy)}</textarea><div class="editor-foot"><span>${state.generating?'正在逐字生成候选版本…':'修改文案后审核状态会自动作废'}</span><span>${state.copy.length} 字</span></div><div class="toolbar" style="margin-top:19px"><button class="button" id="copyText" ${state.copy?'':'disabled'}>▣ 一键复制</button><button class="button" data-step="5" ${state.copy?'':'disabled'}>预览与审核 →</button></div>${validationPanel()}${state.metrics?`<div class="metric-grid"><div class="metric"><strong>${state.copy.length}</strong><small>字数</small></div><div class="metric"><strong>${(state.metrics.duration/1000).toFixed(1)}s</strong><small>耗时</small></div><div class="metric"><strong>${state.metrics.usage?.total_tokens??'—'}</strong><small>Token 消耗</small></div></div>`:''}</div><div class="card compose-side"><h3 class="panel-title">生成上下文</h3><div class="compose-context-group"><span class="compose-context-label">热点</span>${composeNewsCard(n)}</div><div class="compose-context-group"><span class="compose-context-label">已绑定商品</span><div class="compose-product-list">${products.map(composeProductCard).join('')}</div></div><div class="context-row">模型<strong>${state.settings.mode==='mock'?'本地模拟引擎':esc(state.settings.model)}</strong></div><div class="context-row">创作温度<strong>${state.settings.temperature} · 建议 0.7–1.0</strong></div><div class="info-box">提示词独立维护；模型的思考过程不会显示在微博正文中。发布前仍需人工核对文案。</div></div></div>`}
function renderReview(){const n=currentNews(),products=picked();if(!n)return empty('先选择热点','先完成热点选题。',1);if(!products.length)return empty('先绑定商品','绑定商品后再进入审核。',3);if(!state.copy)return empty('先生成文案','完成文案创作后才能预览与审核。',4);
  const okay=n.risk.level==='safe',copyRisk=classifyNews(state.copy),machine=evaluation.verify(state.copy,n,products,state.settings.evaluation);return `<div class="review-layout"><div><div class="content-head"><div><h2>微博卡片预览</h2><p>发布效果为演示预览，不会连接真实微博账号。</p></div><span class="badge ${state.published?'good':state.approved?'good':'warning'}">${state.published?'已模拟发布':state.approved?'审核已通过':'未审核'}</span></div><div class="card weibo-card"><div class="weibo-head"><div class="weibo-avatar">热</div><div><strong>热点精选好物</strong><small>刚刚 · 来自热点营销工作台</small></div></div><div class="weibo-text">${esc(state.copy)}</div><div class="weibo-product-list"><div class="weibo-product-label">关联商品 · ${products.length} 件</div>${products.map(weiboProduct).join('')}</div><div class="weibo-actions"><span>↗ 转发</span><span>♧ 评论</span><span>♡ 赞</span></div></div></div><div class="card review-panel"><h3 class="panel-title">发布前审核</h3><div class="audit-list"><div class="audit-item"><span class="${okay?'ok':'caution'}">●</span><span>热点风险：${okay?'未触发高风险词':'需人工判断，确认适合营销后方可审核'}</span></div><div class="audit-item"><span class="${copyRisk.level==='blocked'?'bad':copyRisk.level==='review'?'caution':'ok'}">●</span><span>文案风险：${copyRisk.level==='blocked'?'包含禁止借势内容，请先修改':copyRisk.level==='review'?'包含敏感议题，需人工核查':'未触发高风险词'}</span></div><div class="audit-item"><span class="ok">●</span><span>商品关联：已绑定 ${products.length} 件商品</span></div><div class="audit-item"><span class="${state.copy.length<=180?'ok':'caution'}">●</span><span>正文长度：${state.copy.length} 字 ${state.copy.length<=180?'':'（建议压缩至 180 字内）'}</span></div><div class="audit-item"><span class="${/#.+#/.test(state.copy)?'ok':'caution'}">●</span><span>话题标签：${/#.+#/.test(state.copy)?'已包含':'建议加入 #话题#'}</span></div></div><div class="review-actions"><button class="button ${state.approved?'soft':'primary'} full" id="approve" ${state.published||copyRisk.level==='blocked'||machine.hardFail?'disabled':''}>${state.approved?'✓ 已通过审核':'✓ 人工审核通过'}</button><button class="button primary full" id="publish" ${state.approved&&!state.published?'':'disabled'}>${state.published?'✓ 模拟发布完成':'↗ 一键发送（模拟）'}</button><button class="button full" data-step="4">返回修改文案</button></div><div class="info-box">本操作仅模拟发送并记录流水，不会调用真实微博发布接口。</div></div></div>`}
function empty(title,description,step){return `<div class="card empty"><div class="empty-icon">✦</div><h3>${title}</h3><p>${description}</p><button class="button primary" data-step="${step}">前往第 ${step} 步 →</button></div>`}
async function fetchHot(){if(state.fetching)return;state.fetching=true;render();if(!state.server){state.sources=[];state.newsMode='demo';state.news=dedupeBatch(normalizeNews(demoNews));if(!state.news.some(n=>n.id===state.selectedNews)){state.selectedNews=null;resetAfterNews()}state.fetching=false;render();toast('本地服务未启动，当前是演示数据');return}
  try{const result=await api('/api/hot',{signal:AbortSignal.timeout(15000)});state.sources=result.sources;state.newsMode=result.mode;state.news=result.mode==='live'?result.news:dedupeBatch(normalizeNews(demoNews));if(!state.news.some(n=>n.id===state.selectedNews)){state.selectedNews=null;resetAfterNews()}toast(result.mode==='live'?`${result.cached?'使用 2 分钟内缓存':'抓取完成'}：${state.news.length} 条，拦截 ${result.blocked} 条，合并重复 ${result.deduped} 条`:'所有来源失败，当前是演示数据');}
  catch(e){state.newsMode='demo';state.news=dedupeBatch(normalizeNews(demoNews));if(!state.news.some(n=>n.id===state.selectedNews)){state.selectedNews=null;resetAfterNews()}state.sources=[{name:'本地服务',status:'failed',count:0,duration:0,error:e.message}];toast('抓取失败，当前是演示数据')}
  state.fetching=false;render();}
async function autoPick(){const candidates=state.news.filter(n=>n.risk.level==='safe');const usable=candidates.find(n=>!recentPublication(n.title,state.records)&&matchProducts(n,state.settings.products).length);if(!usable){toast('自动流程已跳过：没有安全且三天内未发布、又能匹配商品的热点');return}selectNews(usable.id,true);const best=matchProducts(usable,state.settings.products)[0];state.products=[best.product.id];state.recommendedProducts=[best.product.id];resetAfterProduct();state.step=4;render();toast(`自动挑选完成：${usable.title}；已采纳 ${best.product.name}`)}
async function startGeneration(){if(state.repairing||state.generating)return;await refreshSettings();const news=currentNews(),products=picked();if(!news||!products.length){toast('商品配置已更新，请重新绑定商品后生成');render();return}if(news.risk.level==='blocked'){toast('禁止借势热点不能生成文案');return}if(state.settings.mode==='proxy'&&!state.server){toast('本地服务未启动，请切换为本地模拟或启动服务');return}if(state.settings.mode==='direct'&&!state.settings.apiKey){toast('请先在设置中填写浏览器直连密钥');return}
  resetAfterProduct(true);state.toneDrafts.delete(state.variant);const controller=new AbortController();state.controller=controller;state.generating=true;
  const styles=state.settings.creativeStyles||defaults.creativeStyles;
  state.candidates=styles.map(style=>({id:style.id,name:style.name,text:'',status:'pending',metrics:null,validation:null,repairTrace:[],error:''}));state.activeCandidate=styles[0]?.id||null;render();
  let completed=0,failed=0;
  for(const style of styles){
    if(controller.signal.aborted)break;
    const candidate=state.candidates.find(item=>item.id===style.id);if(!candidate)break;
    candidate.status='running';render();
    try{const result=await generate({news,products,settings:{...state.settings,variant:state.variant,creativeStyle:style},onToken:part=>{
      if(controller.signal.aborted)return;
      candidate.text+=part;
      const preview=[...document.querySelectorAll('[data-candidate-preview]')].find(element=>element.dataset.candidatePreview===candidate.id);
      if(preview)preview.textContent=candidate.text.slice(0,76);
      if(state.activeCandidate===candidate.id){state.copy=candidate.text;const editor=$('#copyEditor');if(editor){editor.value=state.copy;editor.scrollTop=editor.scrollHeight;$('.editor-foot span:last-child').textContent=`${state.copy.length} 字`}}
    },signal:controller.signal});
      if(controller.signal.aborted)break;
      candidate.text=result.text;candidate.metrics=result;candidate.status='done';candidate.validation=evaluation.verify(result.text,news,products,state.settings.evaluation);completed++;state.generatedOnce=true;
      if(!state.copy||state.activeCandidate===candidate.id){state.activeCandidate=candidate.id;state.copy=candidate.text;state.metrics=result;state.validation=candidate.validation}
      await saveRecord({type:'generate',title:news.title,products:products.map(p=>p.name),mode:state.settings.mode,model:result.model|| (state.settings.mode==='mock'?'本地模拟':state.settings.model),creativeStyle:style.name,duration:result.duration,usage:result.usage});
    }catch(error){if(error.name==='AbortError'||controller.signal.aborted)break;candidate.status='failed';candidate.error=error.message;failed++;await saveRecord({type:'generate',title:news.title,products:products.map(p=>p.name),mode:state.settings.mode,model:state.settings.mode==='mock'?'本地模拟':state.settings.model,creativeStyle:style.name,status:'failed'});}
    if(!controller.signal.aborted)render();
  }
  if(state.controller!==controller)return;
  state.generating=false;state.controller=null;
  const selected=state.candidates.find(candidate=>candidate.id===state.activeCandidate&&candidate.status==='done')||state.candidates.find(candidate=>candidate.status==='done');
  if(selected){state.activeCandidate=selected.id;state.copy=selected.text;state.metrics=selected.metrics;state.validation=selected.validation}
  else{state.activeCandidate=null;state.copy='';state.metrics=null}
  if(controller.signal.aborted)toast('已停止生成');else if(failed)toast(`生成完成 ${completed} 个版本，${failed} 个失败；可查看失败原因`);else toast(`已生成 ${completed} 个候选版本`);
  render();
}
function selectCandidate(id){const candidate=state.candidates.find(item=>item.id===id&&item.status==='done');if(!candidate||state.generating||state.repairing)return;syncActiveCandidate();state.activeCandidate=id;state.copy=candidate.text;state.metrics=candidate.metrics;state.validation=evaluation.verify(candidate.text,currentNews(),picked(),state.settings.evaluation);state.repairTrace=[...(candidate.repairTrace||[])];syncActiveCandidate();state.approved=false;state.published=false;render();toast(`已选用“${candidate.name}”版本`)}
async function copyText(){try{await navigator.clipboard.writeText(state.copy);toast('文案已复制')}catch{const el=$('#copyEditor');el.select();document.execCommand('copy');toast('文案已复制')}}
async function openSettings(){
  await refreshSettings();const s=state.settings;
  const providerOptions=Object.entries(providerPresets).map(([id,item])=>`<option value="${id}" ${s.provider===id?'selected':''}>${esc(item.name)}</option>`).join('');
  $('#modalRoot').innerHTML=`<div class="overlay" id="overlay"><div class="modal"><div class="modal-head"><h2>工作台快捷设置</h2><button class="button small" id="closeModal">✕</button></div><div class="modal-body"><span class="badge ${state.configSource==='server'?'good':'warning'}">当前配置来源：${state.configSource==='server'?'服务端':state.configSource==='browser'?'浏览器本机':'内置默认值'}</span><div class="modal-note">配置优先级：服务端 → 浏览器本机 → 内置默认值。完整参数和测试连接请到后台“系统配置”。</div><div class="settings-grid"><div class="field span2">接入方式<div class="mode-options"><label><input type="radio" name="mode" value="mock" ${s.mode==='mock'?'checked':''}> 本地模拟</label><label><input type="radio" name="mode" value="proxy" ${s.mode==='proxy'?'checked':''}> 本地服务中转（推荐）</label><label><input type="radio" name="mode" value="direct" ${s.mode==='direct'?'checked':''}> 浏览器直连</label></div></div><label class="field">服务商<select id="configProvider">${providerOptions}</select></label><label class="field">接口基础地址<input id="configBase" value="${esc(s.baseUrl)}"><small>OpenAI 兼容接口；自动补全对话接口路径</small></label><label class="field">模型名称<input id="configModel" value="${esc(s.model)}"></label><label class="field">创作温度<input id="configTemp" type="number" min="0" max="2" step="0.05" value="${s.temperature}"><small>创作建议 0.7–1.0；分类/抽取建议 0–0.3。</small></label><label class="field span2 settings-stream"><input id="configStream" type="checkbox" ${s.stream!==false?'checked':''}> 使用流式输出</label><label class="field span2">浏览器直连密钥<input id="configKey" type="password" autocomplete="off" placeholder="仅直连模式使用" value="${esc(s.apiKey||'')}"><small class="admin-key-warning">只保存在你本机浏览器。正式使用请走服务端中转，把密钥写在服务端配置文件中。</small></label><div class="field span2">抓取来源<small>当前启用 ${s.sources.length} 个内置来源、${(s.rssFeeds||[]).filter(feed=>feed.enabled).length} 个自定义订阅源。<a href="admin-sources.html">到后台管理来源 →</a></small></div><label class="field span2">商品库 JSON<textarea id="configProducts">${esc(JSON.stringify(s.products,null,2))}</textarea><small>在此增删商品，推荐模块会立即复用新配置。</small></label></div></div><div class="modal-foot"><button class="button" id="closeModal2">取消</button><button class="button primary" id="saveSettings">保存设置</button></div></div></div>`;
  $('#configProvider').addEventListener('change',event=>{const preset=providerPresets[event.target.value];if(preset.baseUrl)$('#configBase').value=preset.baseUrl;if(preset.model)$('#configModel').value=preset.model});
}
async function saveSettings(){try{
  const patch={mode:document.querySelector('input[name=mode]:checked').value,provider:$('#configProvider').value,baseUrl:$('#configBase').value.trim(),model:$('#configModel').value.trim(),temperature:Number($('#configTemp').value),stream:$('#configStream').checked,products:JSON.parse($('#configProducts').value)};
  const next={...state.settings,...patch,apiKey:$('#configKey').value.trim()};
  if(!next.products.length)throw new Error('商品列表不能为空');if(!next.model||!next.baseUrl)throw new Error('模型名和接口地址不能为空');if(next.temperature<0||next.temperature>2)throw new Error('温度须在 0 到 2 之间');
  if(state.server){const response=await api('/api/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});state.settings={...defaults,...response.config,apiKey:next.apiKey};state.configSource='server'}else{state.settings=next;state.configSource='browser'}
  localStorage.setItem(localConfigKey,JSON.stringify(state.settings));state.products=state.products.filter(id=>state.settings.products.some(p=>p.id===id));state.recommendedProducts=state.recommendedProducts.filter(id=>state.products.includes(id));resetAfterProduct();$('#modalRoot').innerHTML='';render();toast('设置已保存');
}catch(error){toast(`设置未保存：${error.message}`)}}
function openHistory(){const rows=[...state.records].reverse().slice(0,50);$('#modalRoot').innerHTML=`<div class="overlay" id="overlay"><div class="modal"><div class="modal-head"><h2>操作流水</h2><button class="button small" id="closeModal">✕</button></div><div class="modal-body">${rows.length?rows.map(r=>`<div class="history-item"><strong>${r.type==='fetch'?'抓取热点':r.type==='generate'?'生成文案':'模拟发布'}</strong>　${esc(r.title||`${r.returned||0} 条热点`)}<small>${esc(new Date(r.time).toLocaleString('zh-CN'))}${r.mode?' · '+esc(r.mode):''}${r.duration?' · '+r.duration+' ms':''}</small></div>`).join(''):'<div class="empty">暂无操作流水</div>'}</div></div></div>`}
document.addEventListener('click',async e=>{const target=e.target.closest('button,[data-news]');if(!target)return;
  if(target.id==='manualMode'){if(state.uiMode==='auto')stopAuto();state.uiMode='manual';render();return}
  if(target.id==='autoMode'){state.uiMode='auto';state.autoUnread=0;render();if(!state.autoActive)startAuto();return}
  if(target.dataset.variant){selectVariant(target.dataset.variant);return}
  if(target.dataset.candidate){selectCandidate(target.dataset.candidate);return}
  if(target.dataset.step){state.step=Number(target.dataset.step);render();return}
  if(target.dataset.news){selectNews(target.dataset.news);return}
  if(target.dataset.product){toggleProduct(target.dataset.product);return}
  if(target.dataset.filter){state.filter=target.dataset.filter;render();return}
  switch(target.id){case 'startAuto':startAuto();break;case 'stopAuto':stopAuto();break;case 'runAuto':await runAuto();break;case 'saveAutoThreshold':await saveAutoThreshold();break;case 'fetchHot':await fetchHot();break;case 'autoPick':await autoPick();break;case 'generateCopy':await startGeneration();break;case 'stopGenerate':state.controller?.abort();break;case 'copyText':await copyText();break;case 'repairCopy':await repairCopy();break;case 'settingsOpen':openSettings();break;case 'historyOpen':openHistory();break;case 'closeModal':case 'closeModal2':$('#modalRoot').innerHTML='';break;case 'saveSettings':await saveSettings();break;case 'approve':if(currentNews()?.risk.level==='blocked'||classifyNews(state.copy).level==='blocked'||evaluation.verify(state.copy,currentNews(),picked(),state.settings.evaluation).hardFail){toast('热点或文案存在安全硬伤，请先修正');return}state.approved=true;render();toast('已通过人工审核');break;case 'publish':if(!state.approved||state.published)return;state.published=true;await saveRecord({type:'publish',title:currentNews().title,products:picked().map(p=>p.name),mode:'simulation'});render();toast('模拟发布成功，流水已记录');break;}
});
document.addEventListener('input',e=>{if(e.target.id==='productSearch'){state.query=e.target.value;const pos=e.target.selectionStart;render();const input=$('#productSearch');input.focus();input.setSelectionRange(pos,pos)}if(e.target.id==='copyEditor'){if(state.repairing||state.generating)return;state.copy=e.target.value;state.approved=false;state.published=false;state.metrics=null;state.validation=evaluation.verify(state.copy,currentNews(),picked(),state.settings.evaluation);state.repairTrace=[];syncActiveCandidate();const oldPanel=$('.validation-panel');if(oldPanel)oldPanel.outerHTML=validationPanel();else $('#copyEditor').closest('.compose-main')?.querySelector('.editor-foot + .toolbar')?.insertAdjacentHTML('afterend',validationPanel());$('.editor-foot span:last-child').textContent=`${state.copy.length} 字`;$('#copyText').disabled=!state.copy;document.querySelector('[data-step="5"]:not(.step)')?.toggleAttribute('disabled',!state.copy)}});
document.addEventListener('change',e=>{if(e.target.id==='copyEditor')render()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#modalRoot').innerHTML='';const card=e.target.closest?.('[data-news]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();selectNews(card.dataset.news)}});
init();

})();
